/*==============================================================*/
/* Table: provinces                                             */
/*==============================================================*/
create table provinces (
   id                   SERIAL not null,
   name                 VARCHAR(64)          not null,
   created_at           TIMESTAMP            not null,
   updated_at           TIMESTAMP            not null,
   deleted_at           TIMESTAMP            null,
   constraint PK_PROVINCES primary key (id)
);

/* provinces table data init */
INSERT INTO provinces VALUES (1,'BALI',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (2,'BANGKA BELITUNG',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (3,'BANTEN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (4,'BENGKULU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (5,'DI YOGYAKARTA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (6,'DKI JAKARTA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (7,'GORONTALO',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (8,'JAMBI',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (9,'JAWA BARAT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (10,'JAWA TENGAH',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (11,'JAWA TIMUR',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (12,'KALIMANTAN BARAT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (13,'KALIMANTAN SELATAN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (14,'KALIMANTAN TENGAH',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (15,'KALIMANTAN TIMUR',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (16,'KALIMANTAN UTARA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (17,'KEPULAUAN RIAU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (18,'LAMPUNG',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (19,'MALUKU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (20,'MALUKU UTARA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (21,'NANGGROE ACEH DARUSSALAM (NAD)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (22,'NUSA TENGGARA BARAT (NTB)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (23,'NUSA TENGGARA TIMUR (NTT)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (24,'PAPUA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (25,'PAPUA BARAT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (26,'RIAU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (27,'SULAWESI BARAT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (28,'SULAWESI SELATAN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (29,'SULAWESI TENGAH',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (30,'SULAWESI TENGGARA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (31,'SULAWESI UTARA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (32,'SUMATERA BARAT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (33,'SUMATERA SELATAN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);
INSERT INTO provinces VALUES (34,'SUMATERA UTARA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);