definitions:
  model.Response:
    properties:
      code:
        description: http status code
        type: integer
      data:
        description: main data
      errors:
        additionalProperties: {}
        description: error data
        type: object
      message:
        description: message from system
        type: string
      meta:
        description: support data
      status:
        description: http status message
        type: string
    type: object
info:
  contact: {}
  description: Fetroshop API is a robust and efficient backend solution designed to
    power the online store app named Fetroshop. Developed using the Go programming
    language, this API serves as the backbone for managing the Content Management
    System (CMS) and handling various store-related functionalities.
  title: Fetroshop CMS API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - in: formData
        name: password
        required: true
        type: string
      - in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Login for users
      tags:
      - Authentication
  /api/auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - Bearer: []
      summary: Logout for users
      tags:
      - Authentication
  /api/auth/refresh:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - Bearer: []
      summary: Refresh for customers
      tags:
      - Authentication
  /api/auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: fullName
        required: true
        type: string
      - in: formData
        minLength: 8
        name: password
        required: true
        type: string
      - in: formData
        name: phone
        required: true
        type: string
      - in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Register new user
      tags:
      - Authentication
  /api/category/{code}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - description: Category Code
        in: path
        name: code
        required: true
        type: string
      - in: formData
        name: forceDelete
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Delete category
      tags:
      - Categories
    put:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - description: Category Code
        in: path
        name: code
        required: true
        type: string
      - in: formData
        name: code
        required: true
        type: string
      - in: formData
        name: displayOrder
        required: true
        type: integer
      - in: formData
        name: icon
        type: string
      - in: formData
        name: isActive
        required: true
        type: boolean
      - in: formData
        name: name
        required: true
        type: string
      - in: formData
        name: parentCode
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update category
      tags:
      - Categories
  /api/category/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - in: formData
        name: code
        required: true
        type: string
      - in: formData
        name: displayOrder
        required: true
        type: integer
      - in: formData
        name: icon
        type: string
      - in: formData
        name: isActive
        required: true
        type: boolean
      - in: formData
        name: name
        required: true
        type: string
      - in: formData
        name: parentCode
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Create category
      tags:
      - Categories
securityDefinitions:
  Bearer:
    description: Use format 'Bearer YOUR_TOKEN'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
