definitions:
  model.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: Fetroshop API is a robust and efficient backend solution designed to
    power the online store app named Fetroshop. Developed using the Go programming
    language, this API serves as the backbone for managing the Content Management
    System (CMS) and handling various store-related functionalities.
  title: Fetroshop CMS API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - in: formData
        name: password
        required: true
        type: string
      - in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Login for users
      tags:
      - Authentication
  /api/auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - Bearer: []
      summary: Logout for users
      tags:
      - Authentication
  /api/auth/refresh:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - Bearer: []
      summary: Refresh for customers
      tags:
      - Authentication
  /api/auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: fullName
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      - in: formData
        name: phone
        required: true
        type: string
      - in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Register new user
      tags:
      - Authentication
  /api/category/{categoryCode}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - description: Category Code
        in: path
        name: categoryCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Delete category
      tags:
      - Categories
    put:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - description: Category Code
        in: path
        name: categoryCode
        required: true
        type: string
      - in: formData
        name: code
        type: string
      - in: formData
        name: displayOrder
        type: string
      - in: formData
        name: icon
        type: string
      - in: formData
        name: isActive
        type: string
      - in: formData
        name: name
        type: string
      - in: formData
        name: parentCode
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update category
      tags:
      - Categories
  /api/category/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      parameters:
      - in: query
        name: code
        type: string
      - in: query
        name: displayOrder
        type: string
      - in: query
        name: icon
        type: string
      - in: query
        name: isActive
        type: string
      - in: query
        name: name
        type: string
      - in: query
        name: parentCode
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Create category
      tags:
      - Categories
securityDefinitions:
  Bearer:
    description: Use format 'Bearer YOUR_TOKEN'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
