definitions:
  model.RegistrationRequest:
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    required:
    - email
    - fullName
    - password
    - phone
    - username
    type: object
  model.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: Fetroshop API is a robust and efficient backend solution designed to
    power the online store app named Fetroshop. Developed using the Go programming
    language, this API serves as the backbone for managing the Content Management
    System (CMS) and handling various store-related functionalities.
  title: Fetroshop Web API
  version: "1.0"
paths:
  /api/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.RegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Register new user
      tags:
      - Authentication
securityDefinitions:
  ApiKeyAuth:
    description: Use format 'Bearer YOUR_TOKEN'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
